basePath: /
info:
  contact: {}
  description: This is the API documentation for Microservice A (Data Generator)
  title: sensor-microservice-a
  version: "1.0"
paths:
  /frequency:
    post:
      consumes:
      - application/json
      description: Change how often sensor data is generated.The `freq` parameter
        supports two formats:-- 1. **Milliseconds as integer** (e.g., `1000` = 1 second),
        2. **Go duration string** (e.g., `1s`, `500ms`, `2m`) Example usages:- `POST
        /frequency?freq=1000` → Updates frequency to 1 second, - `POST /frequency?freq=500ms`
        → Updates frequency to 500 milliseconds
      parameters:
      - description: New frequency for sensor data generation (milliseconds or duration
          string)
        in: query
        name: freq
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Frequency successfully updated
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid or missing frequency
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update sensor data generation frequency
      tags:
      - MicroserviceA
swagger: "2.0"
