ALTER TABLE users
    MODIFY COLUMN password VARCHAR(60) NOT NULL,
    ADD COLUMN first_name VARCHAR(255) NULL DEFAULT NULL AFTER id,
    ADD COLUMN last_name VARCHAR(255) NULL DEFAULT NULL AFTER first_name,
    ADD COLUMN last_login DATETIME(6) NULL DEFAULT NULL AFTER role;
